goalquest:
  client:
    task:
      server:
        host: localhost
        port: 8080
      urls:
        base: http://${goalquest.client.task.server.host}:${goalquest.client.task.server.port}/goal
        create: ${goalquest.client.task.urls.base}
        get: ${goalquest.client.task.urls.base}/{id}
        update: ${goalquest.client.task.urls.get}
        complete: ${goalquest.client.task.urls.update}/complete


