app:
  rabbit:
    exchange-name: goal-quest.ex
    queue-name: goal.qu
    routing-key: goal
spring:
  datasource:
    url: jdbc:h2:file:/data/testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

